#server:
#  port: 9070  # The unique port for the order-service
#
#spring:
#  application:
#    name: order-service  # This is the name it will register with Eureka
#  data:
#    mongodb:
#      # This connects to a MongoDB database named 'order_db'.
#      # MongoDB will create it automatically when the service first saves data.
#      uri: mongodb://localhost:27017/order_db
#
#eureka:
#  client:
#    # This tells the service where to find the Eureka server to register itself.
#    # It must be the same for all your microservices.
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    # This helps Eureka identify the service's location for local development.
#    hostname: localhost